#!/bin/bash

# Display start time
echo "🔄 Starting installation - Date and Time: $(date '+%Y-%m-%d %H:%M:%S %Z')"

# Update system
echo "🔄 Updating system..."
sudo apt update && sudo apt upgrade -y
sudo apt install -y python3-pip python3-venv openssh-server curl

# Create virtual environment
echo "📦 Creating virtual environment..."
python3 -m venv venv
source venv/bin/activate

# Install dependencies
echo "📥 Installing dependencies..."
pip install -r requirements.txt

# Initialize database
echo "🗄️ Initializing database..."
python3 -c "from database import init_db; init_db()"

# Collect user input
echo "📝 Please enter the following information:"
read -p "Telegram Bot Token: " bot_token
read -p "Zarinpal Merchant ID (API): " zarinpal_api
read -p "Callback URL (e.g., https://yourdomain.com): " callback_url
read -p "Admin ID (Numeric): " admin_id
read -p "Bot Username (e.g., @YourBotUsername): " bot_username

# Create config.py
echo "📄 Creating configuration file..."
cat > config.py << EOL
# This file is generated by setup.sh
TOKEN = "$bot_token"
ZARINPAL_API = "$zarinpal_api"
CALLBACK_URL = "$callback_url"
ADMIN_ID = $admin_id
BOT_USERNAME = "$bot_username"
EOL

# Set up Webhook
echo "🌐 Setting up Webhook for the bot..."
webhook_url="${callback_url}/webhook/${bot_token}"
curl -X POST "https://api.telegram.org/bot${bot_token}/setWebhook" -d "url=${webhook_url}" -s > /dev/null
if [ $? -eq 0 ]; then
    echo "✅ Webhook set up successfully."
else
    echo "⚠️ Error setting up Webhook. Please check."
fi

# Configure SSH
echo "🔒 Configuring SSH..."
sudo systemctl enable ssh
sudo systemctl start ssh

# Open ports in firewall
echo "🔥 Opening ports (5000 for panel and 8443 for Webhook)..."
sudo ufw allow 5000
sudo ufw allow 8443
sudo ufw --force enable

# Final instructions
echo "✅ Installation completed! Please check the following:"
echo "- Edit servers.json if needed."
echo "- To run: source venv/bin/activate && python bot.py"
echo "- Admin panel: http://your-server-ip:5000/admin"
echo "Completion Date and Time: $(date '+%Y-%m-%d %H:%M:%S %Z')"
